# This file has been generated by node2nix 1.11.1. Do not edit!

{ pkgs ? import <nixpkgs> { } }:

with pkgs;
rustPlatform.buildRustPackage rec {
  pname = "flake-watcher";
  version = "0.1.0";

  src = ./.;

  nativeBuildInputs = [
    rustfmt
  ];
  RUST_SRC_PATH = "${pkgs.rust.packages.stable.rustPlatform.rustLibSrc}";


  cargoLock = {
    lockFile = ./Cargo.lock;
  };

  meta = with stdenv.lib; {
    description = "A fast line-oriented regex search tool, similar to ag and ack";
  };
}
